### ISSUE TITLE
Example doesn't work anymore if Contextable package is upgraded

### ISSUE THREAD

**Issue by tadejstanic** [xpepermint/graphql-example#2]
If you upgrade Contextablejs package to v3.0.0 npm test fails.

The error might occur when the new Model object is instantiated:

```
async getUsers (args) {
      let {User} = this.$context;
      let data = await User.findAll(args);
      return data.map((d) => new User(d) // HERE ); 
    },
```

**Comment by xpepermint** [comment]
Thank you @tadejstanic. Contextable v3 uses the new schema structure. I've upgraded the code - it's using `contextable@^3.0.0`. It should work now.
