### ISSUE TITLE
npm start script not working 

### ISSUE THREAD

**Issue by kevinblanco** [xpepermint/graphql-example#3]
Node v7.9.0
NPM v4.2.0 
Mongo v3.4.3 

running `npm start` returns the following error: 

```> node --harmony ./scripts/graph-start

ERROR: TypeError: this.defineModel is not a function
    at new Root (/Users/hidden/Downloads/graphql-example-master/src/graph/models/root.js:20:10)
    at new Graph (/Users/hidden/Downloads/graphql-example-master/src/graph/index.js:18:22)
    at __dirname (/Users/hidden/Downloads/graphql-example-master/scripts/graph-start.js:7:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)```

**Comment by xpepermint** [comment]
Thx, will check ...

**Comment by kevinblanco** [comment]
Thanks!

**Comment by kevinblanco** [comment]
If it runs well for you, what's your node/npm/mongo versions, so maybe I can get it to run

**Comment by xpepermint** [comment]
Hum... works for me on `node v7.9.0`, `npm v4.2.0`, `mongo v3.2.4`. 
Make sure you run `npm install` or `yarn` before executing `npm start`.

**Comment by xpepermint** [comment]
Ow... you know what ... RawModel package is outdated and I'll have to update the example.

**Comment by kevinblanco** [comment]
Oh ok, about the `npm start` I installed the dependencies with `npm install` and it wasn't working. I tried with `yarn` and now the app is running for me. 

Not sure if the RawModel will be an issue.

**Comment by xpepermint** [comment]
Well... it should work but I'll have to upgrade the example and include the latest RawModel. You can upgrade your models to the latest syntax by following the docs here (for now):  https://github.com/xpepermint/rawmodeljs

**Comment by kevinblanco** [comment]
Thanks!
